spring:
  security:
    oauth2:
      client:
        registration:
          google :
            clientId: 987165691622-9c46j435f8a3fmpcvlbutkqepd78s6jv.apps.googleusercontent.com
            clientSecret: f3bGYfYH8CGoNAykHSmz6Cvu



server:
  port: 9191